DOWNLOADED_VIDEO_PATH = '/mnt/d/Thesis/Data/EnTube/Download'

VIDEO_FPS = 5
AUDIO_FPS = 16000
MAX_SECONDS = 30
TARGET_FRAME_SIZE = (224, 224) # original is about (840, 480)
TARGET_N_FRAME = MAX_SECONDS * VIDEO_FPS
TARGET_AUDIO_LENGTH = MAX_SECONDS * AUDIO_FPS

SUB_FRACTION = 0.3